//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace markustei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPost
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Courses { get; set; }
        public string Email { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Picture { get; set; }
        public string AboutYourSelf { get; set; }
        public string Computer { get; set; }
        public string Engineering { get; set; }
        public string Teaching { get; set; }
        public string Biology { get; set; }
        public string Geographys { get; set; }
        public string Math { get; set; }
        public string Communication { get; set; }
        public string Chemistry { get; set; }
        public string Physics { get; set; }
        public string Law { get; set; }
        public string Economics { get; set; }
        public string Business { get; set; }
        public string Music { get; set; }
        public string Architecture { get; set; }
        public string English { get; set; }
        public string Dentistry { get; set; }
        public string MarineScience { get; set; }
        public string Medicine { get; set; }
        public string Accounting { get; set; }
        public string Anthropology { get; set; }
    }
}
